INSERT INTO GAMELEVEL (NAME) VALUES ('LEVEL 1')
INSERT INTO GAMELEVEL (NAME) VALUES ('LEVEL 2')
INSERT INTO GAMELEVEL (NAME) VALUES ('LEVEL 3')

INSERT INTO PAGE (QUESTION , CORRECTANSWER, GAME_LEVEL_ID) VALUES ( 'vad är 1 + 1?', 2, 1)
INSERT INTO PAGE (QUESTION , CORRECTANSWER, GAME_LEVEL_ID) VALUES ( 'vad är 2 + 1?', 1, 1)
--INSERT INTO PAGE (QUESTION , ANSWER, GAME_LEVEL_ID) VALUES ( 'vad är 2 + 2?',  '4', 1)
--INSERT INTO PAGE (QUESTION , ANSWER, GAME_LEVEL_ID) VALUES ( 'vad är 3 + 2?',  '5', 2)
--INSERT INTO PAGE (QUESTION , ANSWER, GAME_LEVEL_ID) VALUES ( 'vad är 3 + 2?',  '5', 2)

INSERT INTO ANSWER(ANSWER, PAGE_ID) VALUES ('1', 1)
INSERT INTO ANSWER(ANSWER, PAGE_ID) values ('2', 1)
INSERT INTO ANSWER(ANSWER, PAGE_ID) values ('3', 1)
INSERT INTO ANSWER(ANSWER, PAGE_ID) values ('4', 1)
-- Fråga 2
INSERT INTO ANSWER(ANSWER, PAGE_ID) values ('3', 2)
INSERT INTO ANSWER(ANSWER, PAGE_ID) values ('5', 2)
INSERT INTO ANSWER(ANSWER, PAGE_ID) values ('7', 2)
INSERT INTO ANSWER(ANSWER, PAGE_ID) values ('2', 2)


