INSERT INTO PAGE (QUESTION , ANSWER, LEVELSPEL_ID) VALUES ('vad är 1 + 1?', '2', 1)


INSERT INTO LEVELSPEL (NAME) VALUES ('LEVEL 1')
INSERT INTO LEVELSPEL (NAME) VALUES ('LEVEL 2')
INSERT INTO LEVELSPEL (NAME) VALUES ('LEVEL 3')
