INSERT INTO GAMELEVEL (NAME) VALUES ('LEVEL 1')
INSERT INTO GAMELEVEL (NAME) VALUES ('LEVEL 2')
INSERT INTO GAMELEVEL (NAME) VALUES ('LEVEL 3')

INSERT INTO PAGE (QUESTION , ANSWER, GAME_LEVEL_ID) VALUES ( 'vad är 1 + 1?',  '2', 1)
INSERT INTO PAGE (QUESTION , ANSWER, GAME_LEVEL_ID) VALUES ( 'vad är 2 + 1?',  '3', 1)
INSERT INTO PAGE (QUESTION , ANSWER, GAME_LEVEL_ID) VALUES ( 'vad är 2 + 2?',  '4', 1)



